name: Package WordPress Theme

on:
  push:
    tags:
      - '*'  # Triggers on all tag pushes (e.g. v1.0.0)

jobs:
  build-and-release:
    name: Zip and upload theme
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare clean zip folder
        run: |
          mkdir beechagency2023
          shopt -s extglob
          cp -r !(beechagency2023|.git|.github) beechagency2023/
          zip -r beechagency2023.zip beechagency2023

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          files: beechagency2023.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}